config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{ registrations: 'registrations',  omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'places#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places do
    resources :bookings, only: [:new, :create, :edit, :update, :destroy]
    resources :whitelists, only: [:new, :create, :destroy, :index]

  end

  resources :bookings, only: [:index, :destroy]

  resources :invites, only: [:show, :update]

  mount Attachinary::Engine => "/attachinary"

  get '/:friendly_id', to: 'places#show', :as => :friendly_place
end

app/models/whitelist.rb
class Whitelist < ApplicationRecord
  belongs_to :place
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
end

app/controllers/whitelists_controller.rb
class WhitelistsController < ApplicationController

  def index
    skip_policy_scope
    @user = current_user
    @place = Place.friendly.find(params[:place_id])
    @whitelist = Whitelist.new(email: params[:invite_email])
  end

  def create
    @place = Place.friendly.find(params[:place_id])
    @whitelist = Whitelist.new(params_whitelist)
    @whitelist.place = @place
    authorize @whitelist
    if @whitelist.save
      WhitelistMailer.invitation(@whitelist).deliver_now
      redirect_to place_whitelists_path(@place)
    else
      redirect_to place_whitelists_path(@place), alert: "Please enter a valid email"
    end
  end

  def destroy
    @place = Place.friendly.find(params[:place_id])
    @whitelist = Whitelist.find(params[:id])
    authorize @whitelist
    @whitelist.destroy
    redirect_to place_whitelists_path(@place)
  end

   def params_whitelist
    params.require(:whitelist).permit(:email)
  end

end

app/helpers/whitelists_helper.rb
module WhitelistsHelper
end

app/views/whitelists/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div id="background-form">
        <h2>Invite users to access <%= @place.name %>'s calendar </h2>
        <%= render partial: 'places/whitelist_form' %>
      </div>
    </div>
  </div>
  <% if @place.whitelists.present? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div id="background-form">
      <h3>Users authorized to book your place</h3>
        <ul>
          <% @place.whitelists.sort_by{ |whitelist| whitelist.email }.each do |whitelist| %>
          <li> <%= whitelist.email %>  <%= link_to place_whitelist_path(@place, whitelist), method: :delete, data: { confirm: "Are you sure you want to delete #{whitelist.email}?" } do %>
            <i class= 'fa fa-trash-o'></i>
            <% end %>
          </li>
          <% end %>
        </ul>

      <%= link_to 'Check all your places', places_path, class: "btn btn-warning" %>
      <%= link_to "Check this place's page", friendly_place_path(@place), class: "btn btn-warning" %>
      </div>
    </div>
  </div>
  <% end %>
</div>