config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{ registrations: 'registrations',  omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'places#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places do
    resources :bookings, only: [:new, :create, :edit, :update, :destroy]
    resources :whitelists, only: [:new, :create, :destroy, :index]

  end

  resources :bookings, only: [:index, :destroy]

  resources :invites, only: [:show, :update]

  mount Attachinary::Engine => "/attachinary"

  get '/:friendly_id', to: 'places#show', :as => :friendly_place
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :place
  belongs_to :user
  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking)
    @bookings = @bookings.where(user: current_user).order(:start_time).reverse_order
  end


  def new
  end

  def create
    @place = Place.friendly.find(params[:place_id])
    @user = current_user

    @booking = Booking.new(booking_params)
    @booking.place = @place
    @booking.user = @user
    authorize @booking
    if @booking.start_time < Time.current
      redirect_to friendly_place_path(@place), alert: "You cannot book a date in the past"
    elsif @booking.start_time > @booking.end_time
      redirect_to friendly_place_path(@place), alert: "Please choose a start time that is before the end time"
    elsif ( get_days_of_booking(@booking) & @place.non_available_day ).any?
      redirect_to friendly_place_path(@place), alert: "Your booking contains unavailable days of the week. Please check the calendar."
    elsif overlaps?(@place, @booking)
      redirect_to friendly_place_path(@place), alert: "#{@place.name} is already booked at that time. Please check the calendar."
    elsif @booking.save
      BookingMailer.creation_confirmation(@booking).deliver_now
      redirect_to bookings_path
    else
      redirect_to friendly_place_path(@place), alert: "Unexpected error your booking was not saved"
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    authorize @booking
  end
  def update
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to bookings_path, notice: "Your booking has been successfully cancelled"
  end

  private

  def booking_params
    # on doit autoriser le champs de l'élément caché place_id
    params.require(:booking).permit(:start_time, :end_time, :place_id)
  end

  def get_days_of_booking(booking)
    js = booking.start_time.strftime("%j").to_i
    je = booking.end_time.strftime("%j").to_i
    s = booking.start_time.strftime("%w").to_i
    e = booking.end_time.strftime("%w").to_i
    if je - js > 5
      return (0..6).to_a
    elsif s <= e
      return (s..e).to_a
    else
      return (0..6).to_a.reject { |i| ((e + 1)...s).include? i}
    end
  end

  def overlaps?(place, booking)
    st = booking.start_time
    et = booking.end_time
    !place.bookings.where("start_time < ? and end_time > ?", et, st).count.zero?
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/index.html.erb
<div class='container container-place'>
  <div class="place-title">
    <h2>My Bookings
      <%= link_to "<i class= 'fa fa-plus'></i>  Book a new Place".html_safe, places_path, class: "btn btn-warning" %>
    </h2>
  </div>
  <div class="row">
    <% @bookings.each do |booking| %>
      <% image = booking.place.photo ? (cl_image_path booking.place.photo.path) : (image_path 'photo1.jpg')   %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image %>');">
        <div class="card-ribbon">
          <div class="date traditional">
            <p>
              <span class="day_week"><%= booking.start_time.strftime('%a') %></span>
              <span class="day"><%= booking.start_time.strftime('%d') %></span>
              <span class="month"><%= booking.start_time.strftime('%b') %></span>
            </p>
          </div>
        </div>
        <div class="card-description">
            <h2><%= booking.place.name %></h2>
            <p><em><%= booking.place.address %></em></p>
            <span class="small"> <strong>From: </strong><%= booking.start_time.strftime('%H:%M - %d/%m/%Y')%> </span>
            <br>
            <span class="small"><strong>To: </strong><%= booking.end_time.strftime('%H:%M - %d/%m/%Y')%></span>
        </div>
        <div class="card-links">
          <%= link_to "<i class= 'fa fa-home'></i>  Check the place".html_safe, friendly_place_path(booking.place) %>
          <br>
          <%= link_to "<i class= 'fa fa-trash-o'></i> Cancel".html_safe, booking_path(booking), method: :delete, data: { confirm: "Are you really sure you want to cancel this booking?" } %>
        </div>
        <% if Date.today > booking.end_time   %>
          <div class= "card-past text-center"> Past Booking</div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>