config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{ registrations: 'registrations',  omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'places#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places do
    resources :bookings, only: [:new, :create, :edit, :update, :destroy]
    resources :whitelists, only: [:new, :create, :destroy, :index]

  end

  resources :bookings, only: [:index, :destroy]

  resources :invites, only: [:show, :update]

  mount Attachinary::Engine => "/attachinary"

  get '/:friendly_id', to: 'places#show', :as => :friendly_place
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_flashes_home.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible alert-home" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible alert-home" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <ul class="list-inline social-buttons">
    <li>
      <a href="https://twitter.com/matleroux">
        <i class="fa fa-twitter icons-white"></i>
      </a>
    </li>

    <li>
      <a href="https://facebook.com/lewagon">
        <i class="fa fa-facebook icons-white"></i>
      </a>
    </li>

    <li>
      <a href="https://github.com">
        <i class="fa fa-github icons-white"></i>
      </a>
    </li>
  </ul>
  <p class="footer-text">
    calendr.io is a project developped during the Coding Bootcamp program of <a href="http://www.lewagon.com" class="footer-wagon-link">Le Wagon São Paulo</a>
  </p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>


    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if current_user.avatar %>
        <%= cl_image_tag current_user.avatar.path, class: "avatar-bordered dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% elsif current_user.facebook_picture_url %>
            <%= cl_image_tag current_user.facebook_picture_url, class: "avatar-bordered dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
        <%= image_tag "avatardefault.png", class:"avatar-bordered dropdown-toggle", id:"navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to edit_user_registration_path do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "edit your profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to places_path do %>
            <i class="fa fa-home"></i>  <%= t(".places", default: "my places") %>
            <% end %>
          </li>
          <li>
            <%= link_to bookings_path do %>
            <i class="fa fa-calendar-check-o"></i>  <%= t(".bookings", default: "my bookings") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <% else %>

    <!-- Login text link -->
    <%= link_to t(".sign_in", default: "log in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

  </div>

  <% if user_signed_in? %>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to edit_user_registration_path do %>
          <i class="fa fa-user"></i> <%= t(".profile", default: "edit your profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to places_path do %>
          <i class="fa fa-home"></i>  <%= t(".places", default: "my places") %>
          <% end %>
        </li>
        <li>
          <%= link_to bookings_path do %>
          <i class="fa fa-calendar-check-o"></i>  <%= t(".bookings", default: "my bookings") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_navbar_home.html.erb
<div class="navbar-wagon-home navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logowhite.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to t(".features", default: "how it works"), root_path(:anchor => "features-top"), class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to t(".about", default: "about us"), root_path(:anchor => "team"), class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if current_user.avatar %>
        <%= cl_image_tag current_user.avatar.path, class: "avatar-bordered dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% elsif current_user.facebook_picture_url %>
            <%= cl_image_tag current_user.facebook_picture_url, class: "avatar-bordered dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
        <%= image_tag "avatardefault.png", class:"avatar-bordered dropdown-toggle", id:"navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to edit_user_registration_path do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "edit your profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to places_path do %>
            <i class="fa fa-home"></i>  <%= t(".places", default: "my places") %>
            <% end %>
          </li>
          <li>
            <%= link_to bookings_path do %>
            <i class="fa fa-calendar-check-o"></i>  <%= t(".bookings", default: "my bookings") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <% else %>

    <!-- Login text link -->
    <%= link_to t(".sign_in", default: "log in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

  </div>

  <!-- Different navigation if login or not -->
  <% if user_signed_in? %>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to edit_user_registration_path do %>
          <i class="fa fa-user"></i> <%= t(".profile", default: "edit your profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to places_path do %>
          <i class="fa fa-home"></i>  <%= t(".places", default: "my places") %>
          <% end %>
        </li>
        <li>
          <%= link_to bookings_path do %>
          <i class="fa fa-calendar-check-o"></i>  <%= t(".bookings", default: "my bookings") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <% else %>
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li> <%= link_to t(".sign_in", default: "log in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
  <% end %>
</div>