config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{ registrations: 'registrations',  omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'places#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places do
    resources :bookings, only: [:new, :create, :edit, :update, :destroy]
    resources :whitelists, only: [:new, :create, :destroy, :index]

  end

  resources :bookings, only: [:index, :destroy]

  resources :invites, only: [:show, :update]

  mount Attachinary::Engine => "/attachinary"

  get '/:friendly_id', to: 'places#show', :as => :friendly_place
end

app/models/place.rb
class Place < ApplicationRecord
  extend FriendlyId
  validates :name, presence: true
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :whitelists, dependent: :destroy
  accepts_nested_attributes_for :whitelists, reject_if: :all_blank, allow_destroy: true
  has_attachment :photo, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: Proc.new { |a| a.address_changed? && a.latitude.nil? }
  friendly_id :name, use: :slugged
  validates :description, length: { maximum: 150 }
  def non_available_day
    result = []
    result << 0 unless sunday?
    result << 1 unless monday?
    result << 2 unless tuesday?
    result << 3 unless wednesday?
    result << 4 unless thursday?
    result << 5 unless friday?
    result << 6 unless saturday?
    return result
  end

  def array_available_day
    result = []
    result << "Monday" if monday?
    result << "Tuesday" if tuesday?
    result << "Wednesday" if wednesday?
    result << "Thursday" if thursday?
    result << "Friday" if friday?
    result << "Saturday" if saturday?
    result << "Sunday" if sunday?
    return result
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def home
    authorize Place
    render :layout => 'home_layout'
  end

  def index
    @places = policy_scope(Place)
    @places_whitelisted = @places.where(id: Whitelist.where(email: current_user.email).pluck(:place_id))
    @places = @places.where(user: current_user)
  end
  def show
    @place = Place.friendly.find(params[:friendly_id])
    authorize @place
    @user = current_user
    if @place.whitelists.find_by_email(@user.email) || @place.user == @user
      @booking = Booking.new
      @bookings = Booking.where(place: @place)
      @hash = Gmaps4rails.build_markers([@place]) do |place, marker|
        marker.lat place.latitude
        marker.lng place.longitude
      end
      @events = []
      @bookings.each do |booking|
        @events << {title:  "#{booking.user.first_name} #{booking.user.last_name}", start: booking.start_time.iso8601, end: booking.end_time.iso8601, allDay: false}
      end
    else
      redirect_to invite_path(@place)
    end
  end

  def new
    @place = Place.new
    authorize @place
    @place.whitelists.build
  end
  def create
    @place = current_user.places.build(place_params)
    authorize @place
    if @place.save
      PlaceMailer.creation_confirmation(@place).deliver_now
      redirect_to friendly_place_path(@place)
    else
      render :new
    end
  end

  def edit
    @place = Place.friendly.find(params[:id])
    @whitelists = @place.whitelists
    @whitelist = Whitelist.new
    authorize @place
  end

  def update
    @place = Place.friendly.find(params[:id])
    authorize @place
    if @place.update(place_params)
    redirect_to friendly_place_path(@place)
    else
    render :edit
    end
  end

  def destroy
    @place = Place.friendly.find(params[:id])
    authorize @place
    @place.destroy
    redirect_to places_path, notice: "Your place has been successfully cancelled"
  end

  private

  def place_params
    params.require(:place).permit(:latitude, :longitude, :address, :name, :description, :user, :photo, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday, whitelists_attributes: [:id, :email, :_destroy])
  end

end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_calendar.html.erb
<div class="col-xs-12 col-sm-8">
  <div id="calendar" class="calendar-block">
  </div>
</div>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>
  $(document).ready(function() {
    $('#calendar').fullCalendar({
    height: 600,
     views: {
        month: {
        columnFormat: 'dddd',
            <!-- // options apply to month views -->
        },
        week: {
            <!-- // options apply to week views -->
        titleFormat: 'MMMM D YYYY'
        },
        day: {
            <!-- // options day views -->
        }
    },
    <!-- hiddenDays: <%#= raw @place.non_available_day.to_json  %>, -->
    dayRender: function (date, cell) {
        var days = <%= raw @place.non_available_day.to_json  %>;
        len = days.length;

        for (var i = 0;i < len; i++) {
          if (date.day() === days[i]) {
            cell.css("background-color", "grey");
          }
        }
    },

    header: {
    left:"",
    center: 'title',
    right: 'prev,next, month,agendaWeek,agendaDay'
    },
    <!-- start view on month display -->
    defaultView: 'month',
    <!-- start the week on monday -->


    <!-- show end date booking -->
    displayEventEnd: true,
    timeFormat:  'HH:mm',

    events: <%= raw @events.to_json %>,
    eventColor: '#506170'
    });
  });
  <% end %>
<% end %>

app/views/places/_form.html.erb
<%= f.error_notification %>

<div id="place-infos">
  <p><strong>1. Your place infos</strong></p>
  <%= f.input :name, class: 'field', placeholder:"Your place's name" %>
  <%= f.input :address, class: 'field' %>
  <%= f.input :description, class: 'field', placeholder:'Add a description'%>
  <%= f.input :latitude,as: :hidden, input_html: { id: 'latitude'} %>
  <%= f.input :longitude, as: :hidden, input_html: { id: 'longitude'} %>
  <p><strong>2. Refine location</strong></p>
  <p>Drag the marker on the exact location of your place</p>
    <div id="map-simple" class="map-submit"></div>
  <br>
  <p><strong>3. Add a photo</strong></p>
  <%= f.input :photo, as: :attachinary, class: 'field' %>
  <p><strong>4. Define availability</strong></p>
  <%= f.input :monday %>
  <%= f.input :tuesday %>
  <%= f.input :wednesday %>
  <%= f.input :thursday %>
  <%= f.input :friday %>
  <%= f.input :saturday %>
  <%= f.input :sunday %>
</div>
<div id="whitelists">
  <p><strong>5. Define who can access your calendrio</strong></p>
  <p>(you will allow them to book any available slot...)</p>
  <%= f.simple_fields_for :whitelists do |whitelist| %>
    <%= render 'whitelist_fields', f: whitelist %>
  <% end %>
  <div>
  <%= link_to_add_association f, :whitelists, class: "btn btn-secondary" do %>
    <i class='fa fa-user-plus'></i> add another person
  <% end %>
  </div>
</div>
<div style="margin: 25px">
</div>
<div class="col-xs-12 links">
  <hr>
  <%= f.button :submit, class: "btn btn-warning" %>
  <%= link_to 'Cancel', places_path %>
</div>

app/views/places/_form_edit.html.erb
<%= f.error_notification %>

<div id="place-infos">

  <p><strong>
    1. Manage users
  </strong></p>
  <%= link_to 'Edit who can access your calendar', place_whitelists_url(@place), class:'btn btn-warning' %>
  <p><br></p>
  <p><strong>
    2. Your place infos
  </strong></p>


  <%= f.input :name, class: 'field' %>
  <%= f.input :address, class: 'field' %>
  <%= f.input :description, class: 'field'%>
  <%= f.input :latitude,as: :hidden, input_html: { id: 'latitude'} %>
  <%= f.input :longitude, as: :hidden, input_html: { id: 'longitude'} %>

  <p><strong>
    3. Refine location
  </strong></p>
  <p>Drag the marker on the exact location of your place</p>
    <div id="map-simple" class="map-submit"></div>
  <br>
  <p><strong>
    4. Add a photo
  </strong></p>
  <%= f.input :photo, as: :attachinary, class: 'field' %>

  <p><strong>
    5. Define availability
  </strong></p>
  <%= f.input :monday %>
  <%= f.input :tuesday %>
  <%= f.input :wednesday %>
  <%= f.input :thursday %>
  <%= f.input :friday %>
  <%= f.input :saturday %>
  <%= f.input :sunday %>


  <h2 class="personalised-url">Personnalized URL</h2>
  <p>www.calendr.io/<%= @place.slug %></p>

<%= f.button :submit, class: "btn btn-warning" %>

 </div>

app/views/places/_header_show_place.html.erb
<div class="wrapper">
  <div class="container-fluid">
    <div class="row header-place">
      <div id="background-place-header" style="background-image: linear-gradient(-5deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 30%), url('<%= @image %>')">
      </div>
      <div class="container-fluid">
        <div class="row">
          <div class="col-xs-12 col-md-6 header-block">
            <div class="header-item-image">
              <% if @place.photo %>
              <%= cl_image_tag(@place.photo.path,:width=>600, :height=>360, :crop=>"thumb") %>
              <% else %>
              <%= image_tag 'photo1.jpg', class:"place-img-header" %>
              <% end %>
            </div>
          </div>
          <div class="col-xs-12 col-md-6 header-block">
            <div id="map" style="width: 100%; height: 360px;"></div>
            <% content_for(:after_js) do %>
              <%= javascript_tag do %>
                $(document).ready(function() {
                  var handler = Gmaps.build('Google');
                  handler.buildMap({ internal: { id: 'map' } }, function() {
                    markers = handler.addMarkers(<%= raw @hash.to_json %>);
                    handler.bounds.extendWith(markers);
                    handler.fitMapToBounds();
                    if (markers.length == 0) {
                      handler.getMap().setZoom(2);
                    }
                    else if (markers.length == 1) {
                      handler.getMap().setZoom(14);
                    }
                  });
                });
              <% end %>
            <% end %>
          </div>
          <div class="col-xs-12 header-block">
            <div class="place-border-block">
              <h2><%= @place.name %></h2>
              <p>
                <em><%= @place.address %></em>
                <br>
                <%= @place.description %>
              </p>
              <br>
               <p>Available on :<% @place.array_available_day.each do |day| %> <span class="label-day"> <%= day %> </span> <% end %></p>
              <% if @place.user == current_user %>
                <div class="place-button-edit-header">
                  <%= link_to "<i class= 'fa fa-pencil'></i> Edit  ".html_safe, edit_place_path(@place), class: "btn btn-warning" %>
                </div>
                <div class="place-button-invite-header">
                  <%= link_to "<i class= 'fa fa-user-plus'></i> Send invitations".html_safe, place_whitelists_url(@place), class: "btn btn-warning" %>
                </div>
              <% else %>
               <div class="place-owner-header text-right">
                  <br>
                  <% if @place.user.avatar %>
                    <%= cl_image_tag @place.user.avatar.path, class: "avatar-large" %>
                  <% elsif current_user.facebook_picture_url %>
                    <%= cl_image_tag current_user.facebook_picture_url, class: "avatar-large" %>
                  <% else %>
                    <%= image_tag "avatardefault.png", class:"avatar-large" %>
                  <% end %>
                  <br>
                  <%= mail_to @place.user.email, "contact <br> #{@place.user.first_name}", class: "btn btn-warning" %>
                </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/places/_place_booking.html.erb
<div class="col-xs-12 col-sm-4">
  <div class="place-booking-form">
    <h3>Make a booking</h3>
    <%= simple_form_for [@place, @booking] do |f| %>
    <%= f.input :start_time, as: :string, label: 'I want to book from...', input_html: { class: 'datepickermin' } %>
    <%= f.input :end_time, as: :string, label: '...up until...', input_html: { class: 'datepickermin' } %>
    <%= f.button :submit, 'Book it :)', class: "btn btn-warning" %>
    <% end %>
  </div>
</div>

app/views/places/_whitelist_fields.html.erb
<div class="nested-fields field">
  <div class="container">
    <div class="row" style="width: 580px">
      <div class="col-xs-8">
        <%= f.input :email, label: false, placeholder: "someone_you_trust@email.com" %>
      </div>
      <div class="col-xs-4">
        <%= link_to_remove_association "<i class='fa fa-user-times'></i> remove email".html_safe, f, height: '30px', class:"btn btn-secondary" %>
      </div>
    </div>
  </div>

</div>

app/views/places/_whitelist_form.html.erb
<%= simple_form_for [@place, @whitelist] do |f| %>
<%= f.input :email %>

<%= f.button :submit, "Add this email", class: "btn btn-warning" %>
<% end %>

app/views/places/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div id="background-form">
        <h1>Update the place <%= @place.name%></h1>
        <%= simple_form_for(@place) do |f| %>
        <%= render partial: 'form_edit', locals: {f: f} %>
        <% end %>
        <br>
        <%= link_to 'Back', places_path %>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    var _latitude = <%= @place.latitude %>;
    var _longitude = <%= @place.longitude %>;
    var _zoom = 16;
    setupNewPlace(_latitude, _longitude, _zoom);

  <%end%>
<%end%>

app/views/places/home.html.erb
<% num = rand(1..6).to_s %>
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path 'photo' + num + '.jpg' %>');">
  <%= render 'shared/navbar_home' %>
  <%= render 'shared/flashes_home' %>
  <div class="banner-content" >
    <%= image_tag "logowhitenopin.png", height:'70px' %>
    <br>
    <br>
    <p>The easiest way to manage calendars for <span class="element"></span></p>
    <%= link_to new_place_path, class:'btn btn-warning' do %>
      create your own <%= image_tag "pinwhite.png", height:'30px' %>
    <%end%>
  </div>
</div>
<div class="arrow bounce">
  <a class="fa fa-chevron-down fa-2x links" href="#features-top"></a>
</div>
<div id="features-top"></div>
<section id="features">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
          <h2 class="section-heading">The first calendar made for shared space</h2>
          <br>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-md-4">
          <span class="fa-stack fa-4x">
              <i class="fa fa-circle fa-stack-2x icons-orange"></i>
              <i class="fa fa-location-arrow fa-stack-1x fa-inverse"></i>
          </span>
          <h4 class="features-heading">Beautiful</h4>
          <p class="text-muted">Your place deserves more than just a dull calendar. Bring pictures, maps and a sleek design and <strong>get your users to go "wow"</strong>... </p>
      </div>
      <div class="col-md-4">
          <span class="fa-stack fa-4x">
              <i class="fa fa-circle fa-stack-2x icons-orange"></i>
              <i class="fa fa-laptop fa-stack-1x fa-inverse"></i>
          </span>
          <h4 class="features-heading">Accessible</h4>
          <p class="text-muted">No more paper or lost email, share the link of the calendar with anyone you want and let them book anytime. <strong>Bad surprise? No more.</strong></p>
      </div>
      <div class="col-md-4">
          <span class="fa-stack fa-4x">
              <i class="fa fa-circle fa-stack-2x icons-orange"></i>
              <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
          </span>
          <h4 class="features-heading">Private</h4>
          <p class="text-muted"><strong>You and only you are in charge</strong> of who gets access and can create bookings on your place. Easily add or remove any user from your calendar.</p>
      </div>
    </div>
    <div class="row text-center">
    <br>
      <%= link_to new_place_path, class:'btn btn-warning' do %>
       create your first calendr.io <%= image_tag "pinwhite.png", height:'30px' %>
      <%end%>
    </div>
  </div>
</section>
<section id="team" class="bg-light-gray">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 text-center">
          <h2 class="section-heading">About us</h2>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="team-member text-center">
          <%= image_tag "Roger.png", class:'avatar-bordered-large' %>
          <h4>Roger Scott</h4>
          <p class="text-muted">Lead Developper</p>
          <ul class="list-inline social-buttons icons-orange">

            <li>
                <a href="">
                    <i class="fa fa-twitter icons-orange"></i>
                </a>
            </li>

            <li>
                <a href="https://github.com/rogerpscott/">
                    <i class="fa fa-github icons-orange"></i>
                </a>
            </li>

            <li>
                <a href="https://br.linkedin.com/in/roger-scott-322a0461/en">
                    <i class="fa fa-linkedin icons-orange"></i>
                </a>
            </li>

          </ul>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="team-member text-center">
          <%= image_tag "Jon.png", class:'avatar-bordered-large' %>
          <h4>Jonathan Chevalier</h4>
          <p class="text-muted">Fullstack Developper</p>
          <ul class="list-inline social-buttons">

              <li>
                  <a href="https://twitter.com/Jojoooo1">
                      <i class="fa fa-twitter icons-orange"></i>
                  </a>
              </li>

              <li>
                  <a href="https://github.com/Jojoooo1">
                      <i class="fa fa-github icons-orange"></i>
                  </a>
              </li>

              <li>
                  <a href="https://www.linkedin.com/in/jonathan-chevalier-18b4ba57">
                      <i class="fa fa-linkedin icons-orange"></i>
                  </a>
              </li>


          </ul>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="team-member text-center">
          <%= image_tag "mat.png", class:'avatar-bordered-large' %>
          <h4>Mathieu Le Roux</h4>
          <p class="text-muted">Fullstack Developer</p>
          <ul class="list-inline social-buttons icons-orange">

              <li>
                  <a href="https://twitter.com/matleroux">
                      <i class="fa fa-twitter icons-orange"></i>
                  </a>
              </li>

              <li>
                  <a href="https://github.com/matleroux">
                      <i class="fa fa-github icons-orange"></i>
                  </a>
              </li>

              <li>
                  <a href="https://www.linkedin.com/in/matleroux">
                      <i class="fa fa-linkedin icons-orange"></i>
                  </a>
              </li>


          </ul>
        </div>
      </div>
  </div>
</section>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function(){
        $(".element").typed({
            strings: ["^0shared spaces", "^3000 a meeting room", "^2000 a tennis court", "^2000 your family cabin", "^2000 or a shared boat","^2000 ...","^2000 any shared space..."],
            typeSpeed: 0
        });
    });
  <% end %>
  <%= javascript_tag do %>
    $(document).ready(function(){
      $(window).scroll(function() {
        var scroll = $(window).scrollTop();

        if (scroll >= 190) {
          $('.navbar-wagon-home').addClass('post-scroll');
        } else {
          $('.navbar-wagon-home').removeClass('post-scroll');
        }
      });
    });
  <% end %>
<% end %>

app/views/places/index.html.erb
<div class='container container-place'>
  <div class="place-title">
    <h2>My Places
      <%= link_to "Create a new place", new_place_path, class: "btn btn-warning" %>
    </h2>
  </div>
  <div class="row">
    <% @places.each do |place| %>
      <% image = place.photo ? (cl_image_path place.photo.path) : (image_path 'photo1.jpg')   %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image %>');">
        <div class="card-category"><%= place.name%></div>
        <div class="card-description">
          <p><%= place.address %></p>
        </div>
        <div class="card-links">
          <%= link_to "<i class= 'fa fa-pencil'></i>  Edit".html_safe, edit_place_path(place) %>
          <br>
          <%= link_to "<i class= 'fa fa-trash-o'></i>  Remove".html_safe, place_path(place), method: :delete, data: { confirm: "Are you really sure you want to delete the place?" } %>
        </div>
        <%= link_to "", friendly_place_path(place), class: "card-link" %>
      </div>
    <% end %>
  </div>
    <div class="place-title">
    <h2>The Places I can book</h2>
  </div>
  <div class="row">
    <% @places_whitelisted.each do |place| %>
      <% image = place.photo ? (cl_image_path place.photo.path) : (image_path 'photo1.jpg')   %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image %>');">
      <div class="card-category"><%= place.name%></div>
      <div class="card-description">
        <p><%= place.address %></p>
      </div>
      <div class="card-links">
        <%= link_to "<i class= 'fa fa-calendar-check-o'></i>  Book".html_safe, friendly_place_path(place) %>
        <br>
      </div>
      <%= link_to "", friendly_place_path(place), class: "card-past" %>
      </div>
    <% end %>
  </div>
</div>

app/views/places/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div id="background-form">
        <h1>Create a new place</h1>
        <%= simple_form_for(@place) do |f| %>
          <%= render partial: 'form', locals: {f: f} %>
        <% end %>
        <br>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    var _latitude = 43.118999;
    var _longitude = 5.936625;
    var _zoom = 2;
    setupNewPlace(_latitude, _longitude, _zoom);
  <%end%>
<%end%>

app/views/places/show.html.erb
 <% @image = @place.photo ? (cl_image_path @place.photo.path) : (image_path 'photo1.jpg')   %>

 <%= render 'header_show_place'%>

<div class="wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="calendar-form-block">
        <%= render 'places/calendar' %>
        <%= render 'places/place_booking', place: @place %>
      </div>
    </div>
  </div>
</div>
<%= render 'calendar' %>